name: Run Vitest frontend tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        working-directory: ./front end/Ransomware Hunter
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: ./front end/Ransomware Hunter
      - name: Execute Unit tests
        run: npm run test
        working-directory: ./front end/Ransomware Hunter
